package org.kotyle.squall.db.column

import org.kotyle.squall.mapper.table.Table
import org.slf4j.LoggerFactory
import java.sql.Types

val log = LoggerFactory.getLogger("org.kotyle.squall.db.column")

interface LengthConstrained { abstract val maxLength: Int }

enum class GenerationStrategy {
    NONE,
    AUTO
}

open class Column(val table: Table,
                  val name: String,
                  val type: Int,
                  val nullable: Boolean = false,
                  val autoGenerated: GenerationStrategy = GenerationStrategy.NONE) {
    init {
        table._columns.add(this)
    }
}
open class LengthConstrainedColumn(table: Table, name: String, type: Int, override val maxLength: Int): Column(table, name, type), LengthConstrained

class VarChar(table: Table, name: String, val maxLen: Int): LengthConstrainedColumn(table, name, Types.VARCHAR, maxLen) {}
class BigInt(table: Table, name: String, autoGenerated: GenerationStrategy = GenerationStrategy.NONE): Column(table, name, Types.BIGINT, autoGenerated=autoGenerated){}
